all:
	gcc deleteNodeWithoutHead.c -o deleteNodeWithoutHead.o
	gcc deleteNodeDoublePtr.c -o deleteNodeDoublePtr.o
	g++ recoverTheArrays.cpp -o recoverTheArrays.o 
	g++ sumOfAllNumbers.cpp -o sumOfAllNumbers.o
	g++ bubbleSort.cpp -o bubbleSort.o
	g++ plusOne.cpp -o plusOne.o
	g++ balancedParenthesis.cpp -o  balancedParenthesis.o
	g++ climbingStairs.cpp -o climbingStairs.o
	g++ cycleInLinkedList.cpp -o cycleInLinkedList.o
	g++ gradingStudents.cpp -o gradingStudents.o
	g++ matchboxThief.cpp -o matchboxThief.o
	g++ maximumSubarraySum.cpp -o maimumSubarraySum.o
	g++ mergeTwoSortedList.cpp -o mergeTwoSortedList.o
	g++ swapNodesAlgo.cpp -o swapNodesAlgo.o
	g++ singleNumber.cpp -o singleNumber.o

clean:
	rm *.o
